[
  {
    asin: "B0BQ118F2T",
    product_title:
      "Moto G Play 2023 3-Day Battery Unlocked Made for US 3/32GB 16MP Camera Navy Blue",
    product_price: "$99.99",
    product_original_price: "$169.99",
    currency: "USD",
    product_star_rating: "4",
    product_num_ratings: 2928,
    product_url: "https://www.amazon.com/dp/B0BQ118F2T",
    product_photo:
      "https://m.media-amazon.com/images/I/61K1Fz5LxvL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 10,
    product_minimum_offer_price: "$64.89",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "5K+ bought in past month",
    delivery: "FREE delivery Tue, Aug 6",
    has_variations: true,
  },
  {
    asin: "B0CTD47P22",
    product_title:
      "SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Light Blue)",
    product_price: "$149.74",
    product_original_price: "$158.00",
    currency: "USD",
    product_star_rating: "4.2",
    product_num_ratings: 135,
    product_url: "https://www.amazon.com/dp/B0CTD47P22",
    product_photo:
      "https://m.media-amazon.com/images/I/51QhB2CfqSL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 9,
    product_minimum_offer_price: "$145.87",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    product_availability: "Only 2 left in stock - order soon.",
    climate_pledge_friendly: false,
    sales_volume: "3K+ bought in past month",
    delivery: "FREE delivery Wed, Aug 7 Only 2 left in stock - order soon.",
    has_variations: false,
  },
  {
    asin: "B0CHH6X6H2",
    product_title:
      "Total by Verizon | Samsung Galaxy A03s | Locked | 32GB | 5000mAh Battery | 48MP Main Camera | 6.5-in. HD+Infinity-V Display | Black",
    product_price: "$49.88",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4",
    product_num_ratings: 204,
    product_url: "https://www.amazon.com/dp/B0CHH6X6H2",
    product_photo:
      "https://m.media-amazon.com/images/I/812woqv69CL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$49.88",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "2K+ bought in past month",
    delivery: "FREE delivery Tue, Aug 6 Or fastest delivery Tomorrow, Aug 2",
    has_variations: false,
  },
  {
    asin: "B0BZ9XNBRB",
    product_title:
      "Google Pixel 7a - Unlocked Android Cell Phone - Smartphone with Wide Angle Lens and 24-Hour Battery - 128 GB – Charcoal",
    product_price: "$340.00",
    product_original_price: "$499.00",
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: 2248,
    product_url: "https://www.amazon.com/dp/B0BZ9XNBRB",
    product_photo:
      "https://m.media-amazon.com/images/I/61r7cCpQPlL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 33,
    product_minimum_offer_price: "$299.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    product_availability: "Only 3 left in stock - order soon.",
    climate_pledge_friendly: false,
    sales_volume: "10K+ bought in past month",
    delivery: "FREE deliveryOnly 3 left in stock - order soon.",
    has_variations: true,
  },
  {
    asin: "B0CV4NQYFP",
    product_title:
      "SAMSUNG Galaxy A35 5G A Series Cell Phone, 128GB Unlocked Android Smartphone, AMOLED Display, Advanced Triple Camera System, Expandable Storage, Rugged Design, US Version, 2024, Awesome Navy",
    product_price: "$349.99",
    product_original_price: "$399.99",
    currency: "USD",
    product_star_rating: "4.4",
    product_num_ratings: 109,
    product_url: "https://www.amazon.com/dp/B0CV4NQYFP",
    product_photo:
      "https://m.media-amazon.com/images/I/71OznGGxhcL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 2,
    product_minimum_offer_price: "$267.01",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: true,
    sales_volume: "3K+ bought in past month",
    delivery: "FREE delivery Tue, Aug 6 Or fastest delivery Tomorrow, Aug 2",
    has_variations: true,
  },
  {
    asin: "B0CSB22F9C",
    product_title:
      "Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Light Blue)",
    product_price: "$129.99",
    product_original_price: "$137.65",
    currency: "USD",
    product_star_rating: "4.2",
    product_num_ratings: 578,
    product_url: "https://www.amazon.com/dp/B0CSB22F9C",
    product_photo:
      "https://m.media-amazon.com/images/I/51rp0nqaPoL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 15,
    product_minimum_offer_price: "$128.12",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "3K+ bought in past month",
    delivery: "FREE delivery Tue, Aug 6 Or fastest delivery Tomorrow, Aug 2",
    has_variations: false,
  },
  {
    asin: "B09V5LDZQ4",
    product_title:
      "Samsung Galaxy S22 Smartphone, Factory Unlocked Android Cell Phone, 128GB, 8K Camera &amp; Video, Brightest Display, Long Battery Life, Fast 4nm Processor, US Version, Phantom Black (Renewed)",
    product_price: "$252.77",
    product_original_price: "$379.99",
    currency: "USD",
    product_star_rating: "4.1",
    product_num_ratings: 1806,
    product_url: "https://www.amazon.com/dp/B09V5LDZQ4",
    product_photo:
      "https://m.media-amazon.com/images/I/61kfOWlQLsL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 35,
    product_minimum_offer_price: "$158.21",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery Tue, Aug 6",
    has_variations: true,
  },
  {
    asin: "B0CGTD5KVT",
    product_title:
      "Google Pixel 8 - Unlocked Android Smartphone with Advanced Pixel Camera, 24-Hour Battery, and Powerful Security - Obsidian - 128 GB",
    product_price: "$543.90",
    product_original_price: "$699.00",
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: 2098,
    product_url: "https://www.amazon.com/dp/B0CGTD5KVT",
    product_photo:
      "https://m.media-amazon.com/images/I/81Mya-dPIOL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 10,
    product_minimum_offer_price: "$409.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    product_availability: "Only 12 left in stock - order soon.",
    climate_pledge_friendly: false,
    sales_volume: "2K+ bought in past month",
    delivery:
      "FREE delivery Sat, Aug 3 Or fastest delivery Tomorrow, Aug 2 Only 12 left in stock - order soon.",
    has_variations: true,
  },
  {
    asin: "B0CMDRFVTL",
    product_title:
      "SAMSUNG Galaxy S24 Cell Phone, 256GB AI Smartphone, Unlocked Android, 50MP Camera, Fastest Processor, Long Battery Life, US Version, 2024, Cobalt Violet",
    product_price: null,
    product_original_price: null,
    currency: null,
    product_star_rating: "4.3",
    product_num_ratings: 262,
    product_url: "https://www.amazon.com/dp/B0CMDRFVTL",
    product_photo:
      "https://m.media-amazon.com/images/I/716UvwH-NvL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: null,
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: true,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery Tue, Aug 6 Or fastest delivery Tomorrow, Aug 2",
    has_variations: true,
  },
  {
    asin: "B0CP6DDN1H",
    product_title:
      "Moto G Play | 2024 | Unlocked | Made for US 4/64GB | 50MP Camera | Sapphire Blue",
    product_price: "$129.99",
    product_original_price: "$149.99",
    currency: "USD",
    product_star_rating: "4.1",
    product_num_ratings: 94,
    product_url: "https://www.amazon.com/dp/B0CP6DDN1H",
    product_photo:
      "https://m.media-amazon.com/images/I/61xk4XNRktL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 4,
    product_minimum_offer_price: "$94.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery Tue, Aug 6 Or fastest delivery Tomorrow, Aug 2",
    has_variations: false,
  },
  {
    asin: "B0C2S6TKTL",
    product_title:
      "Motorola Moto G Stylus 5G | 2023 | Unlocked | Made for US 6/256GB | 50 MPCamera | Cosmic Black, 162.83x73.77x9.29",
    product_price: "$229.99",
    product_original_price: "$399.99",
    currency: "USD",
    product_star_rating: "4.2",
    product_num_ratings: 3123,
    product_url: "https://www.amazon.com/dp/B0C2S6TKTL",
    product_photo:
      "https://m.media-amazon.com/images/I/61O66kJiiGL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 6,
    product_minimum_offer_price: "$184.31",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery Tue, Aug 6 Or fastest delivery Tomorrow, Aug 2",
    has_variations: false,
  },
  {
    asin: "B0CN1QSH8Q",
    product_title:
      "SAMSUNG Galaxy A15 5G A Series Cell Phone, 128GB Unlocked Android Smartphone, AMOLED Display, Expandable Storage, Knox Security, Super Fast Charging, Hi-Res Camera, US Version, 2024, Blue Black",
    product_price: "$199.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.1",
    product_num_ratings: 422,
    product_url: "https://www.amazon.com/dp/B0CN1QSH8Q",
    product_photo:
      "https://m.media-amazon.com/images/I/61s0ZzwzSCL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 2,
    product_minimum_offer_price: "$150.09",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: true,
    sales_volume: "3K+ bought in past month",
    delivery: "FREE delivery Tue, Aug 6",
    has_variations: true,
  },
  {
    asin: "B0CTBCDCDH",
    product_title:
      "SAMSUNG Galaxy A05s (SM-A057M/DS), 128GB 4GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Light Violet)",
    product_price: "$119.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.1",
    product_num_ratings: 38,
    product_url: "https://www.amazon.com/dp/B0CTBCDCDH",
    product_photo:
      "https://m.media-amazon.com/images/I/21f9A+OzosL._AC_UY365_FMwebp_QL65_.jpg",
    product_num_offers: 9,
    product_minimum_offer_price: "$117.25",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "300+ bought in past month",
    delivery: "FREE delivery Tue, Aug 6 Or fastest delivery Mon, Aug 5",
    has_variations: false,
  },
  {
    asin: "B00FRSYS12",
    product_title:
      "VTech CS6719-2 2-Handset Expandable Cordless Phone with Caller ID/Call Waiting, Handset Intercom &amp; Backlit Display/Keypad, Silver",
    product_price: "$38.82",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.4",
    product_num_ratings: 37515,
    product_url: "https://www.amazon.com/dp/B00FRSYS12",
    product_photo:
      "https://m.media-amazon.com/images/I/71HLNfFVCcL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 25,
    product_minimum_offer_price: "$19.85",
    is_best_seller: false,
    is_amazon_choice: true,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "3K+ bought in past month",
    delivery: "FREE delivery Tue, Aug 6 Or fastest delivery Tomorrow, Aug 2",
    has_variations: false,
  },
  {
    asin: "B0D5T7318W",
    product_title:
      "Bold K10 | 2024 | 3-Day Battery | Unlocked | 6.6” HD+ Infinity Display | 128/4GB | Triple 50MP Camera | US Version | US Warranty | Black",
    product_price: "$99.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "3.8",
    product_num_ratings: 8,
    product_url: "https://www.amazon.com/dp/B0D5T7318W",
    product_photo:
      "https://m.media-amazon.com/images/I/716qo4kxJzL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 4,
    product_minimum_offer_price: "$99.95",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "200+ bought in past month",
    delivery: "FREE delivery Tue, Aug 6 Or fastest delivery Mon, Aug 5",
    has_variations: false,
  },
  {
    asin: "B09T3MQSVP",
    product_title:
      "Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM Unlocked Android Smartphone, 64GB, Long Lasting Battery, Expandable Storage, Triple Lens Camera, Infinite Display, Black (Renewed)",
    product_price: "$98.49",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "3.8",
    product_num_ratings: 1269,
    product_url: "https://www.amazon.com/dp/B09T3MQSVP",
    product_photo:
      "https://m.media-amazon.com/images/I/61xhaqnlKPL._AC_UY654_FMwebp_QL65_.jpg",
    product_num_offers: 22,
    product_minimum_offer_price: "$77.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    product_availability: "Only 2 left in stock - order soon.",
    climate_pledge_friendly: false,
    sales_volume: "500+ bought in past month",
    delivery: "FREE delivery Aug 2 - 5 Only 2 left in stock - order soon.",
    has_variations: false,
  },
];
